# Generated by Django 4.2.4 on 2023-08-16 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.CharField(max_length=400)),
                ('cv', models.FileField(upload_to='cover_letters')),
                ('occupation', models.CharField(max_length=255)),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.event')),
            ],
        ),
    ]
