# Generated by Django 4.2.1 on 2023-08-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0008_alter_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(default='ticket_qr/qrcode.png', upload_to='ticket_qr'),
        ),
    ]
