# Generated by Django 4.2.1 on 2023-09-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0010_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='image',
            field=models.ImageField(default='users/person.png', upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='events/event1.jpg', upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(default='ticket_qr/qrcode.png', upload_to='ticket_qr/'),
        ),
    ]
